cat > ./arch/arm64/configs/vendor/sps.config <<'EOF'
CONFIG_CONFIG_NO_HZ_FULL=y
CONFIG_CONFIG_HZ_100=y
CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL=n
CONFIG_CPU_FREQ_DEFAULT_GOV_POWERSAVE=y
CONFIG_ARM_CPUIDLE=y
CONFIG_CPUFREQ_DT=y
CONFIG_SCHED_SMT=y
CONFIG_SCHED_AUTOGROUP=y
CONFIG_SCHED_DEBUG=n
CONFIG_PM_DEVFREQ_EVENT=y
CONFIG_DEVFREQ_GOV_POWERSAVE=y
CONFIG_DEVFREQ_THERMAL=y
CONFIG_GENERIC_ADC_THERMAL=y
EOF

make $args vendor/sps.config